const colors = {
  light: {
    text: "#E2EAFF",
    tint: "#3B82F6",
    background: "#0B0E15",
    foreground: "#E2EAFF",
    card: "#121929",
    cardForeground: "#E2EAFF",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#1A2740",
    secondaryForeground: "#8BA4CA",
    muted: "#141F30",
    mutedForeground: "#5C7BA0",
    accent: "#0EA47E",
    accentForeground: "#FFFFFF",
    destructive: "#E53E3E",
    destructiveForeground: "#FFFFFF",
    border: "#1E2C45",
    input: "#141F30",
    online: "#0EA47E",
  },
  dark: {
    text: "#E2EAFF",
    tint: "#3B82F6",
    background: "#0B0E15",
    foreground: "#E2EAFF",
    card: "#121929",
    cardForeground: "#E2EAFF",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#1A2740",
    secondaryForeground: "#8BA4CA",
    muted: "#141F30",
    mutedForeground: "#5C7BA0",
    accent: "#0EA47E",
    accentForeground: "#FFFFFF",
    destructive: "#E53E3E",
    destructiveForeground: "#FFFFFF",
    border: "#1E2C45",
    input: "#141F30",
    online: "#0EA47E",
  },
  radius: 14,
};

export default colors;
